#!/bin/bash

<<COMMENT
Input:
1. structure.pdb
COMMENT

echo '
-in:file:s structure.pdb
-compute_packstat true
-tracer_data_print false
-out:file:score_only pack_input_score.sc
-pack_input true
-pack_separated true
-add_regular_scores_to_scorefile true
-atomic_burial_cutoff 0.01
-sasa_calculator_probe_radius 1.4
-pose_metrics::interface_cutoff 8.0
-use_input_sc
'>flags

{ROSETTA}/main/source/bin/InterfaceAnalyzer.default.linuxgccrelease @flags
