#!/bin/bash

<<COMMENT
Input:
1. protein.pdb
2. scaffold_AZIZprotocol.xml 
COMMENT

grep " A " protein.pdb > receptor.pdb
perl {PATH}/slicePdb_Ubuntu.pl protein.pdb B 420 429 > epitope.pdb
perl {PATH}/sequentialPdbResSeq.pl -pdbfile epitope.pdb > motif.pdb
rm epitope.pdb
cp {PATH}/scaffold_AZIZprotocol.xml {PATH}/epigraft

echo '
#!/bin/bash
#PBS -N epigraft
#PBS -q fat
#PBS -l select=1:ncpus=1
#PBS -j oe
#PBS -J 1-500

mkdir -p {PATH}/res_${PBS_ARRAY_INDEX}
{ROSETTA}/main/source/bin/rosetta_scripts.default.linuxgccrelease -database {ROSETTA}/main/database -l {PATH}/inputlist/inputlist_${PBS_ARRAY_INDEX} -overwrite -out:file:renumber_pdb true -ex1 -ex2 -ignore_zero_occupancy false -parser:protocol /fefs1/generic/ssabban/Allergy_Vaccine_FG/epigraft/scaffold_AZIZprotocol.xml -ignore_unrecognized_res -nstruct 1 -out:path:all {PATH}/res_${PBS_ARRAY_INDEX}
'>epigraft.pbs
