#!/bin/bash

#Run script from inside the results directory
mkdir scaffolds_bad_size
mkdir scaffolds_good_size
mkdir chosen
find . -name '*.pdb' -exec mv {} scaffolds_bad_size \;
find . -type f -name '*.sc' -exec cat {} + > scores.sc
grep SCORE scores.sc | sort -nk +2 | awk '{print $2 "\t" $4 "\t" $13 "\t" $23 "\t" $32}' > sorted_scores
sed -i "/description/d}" sorted_scores
rm -r res_*

for file in *.pdb; do
        CHAINAnumb=`grep ATOM $file | awk '{print $5 "\t" $6}' | grep A | tail -n 1 | awk '{print $2}'`
        CHAINBnumb=`grep ATOM $file | awk '{print $5 "\t" $6}' | grep B | tail -n 1 | awk '{print $2}'`

        [[ $CHAINBnumb = *[!0-9]* || $CHAINAnumb = *[!0-9]* ]] && continue

        AminoAcids=$((CHAINBnumb-CHAINAnumb))
        echo $AminoAcids

        if (( $AminoAcids \< 150 ))
                then
                        mv $file scaffolds_good_size;
        fi
done
