#!/bin/bash

<<COMMENT
Input Files:
1. structure.pdb
COMMENT

echo '
-database {ROSETTA}/main/database
-ignore_unrecognized_res
-s structure.pdb
-cp:max_failures 5
-cp:cutoff 3.0
-sasa_calculator_probe_radius 1.0
#-cp:print_intermediate_pdbs
#-cp:exclude_file no_mut
-cp:local_relax
-cp:relax_mover "relax"
-cp:print_reports
-mute protocols.simple_moves core.pack protocols::checkpoint protocols.relax core.scoring.etable basic.io.database core.io.pdb core.chemical protocols.packstat
'>flags

{ROSETTA}/main/source/bin/vip.default.linuxgccrelease @flags
