import torch # pip install torch numpy pandas scikit-learn
import sklearn
import numpy as np
import pandas as pd
from sklearn import model_selection

'''
https://www.youtube.com/watch?v=Z_ikDlimN6A

Concepts:
=========
We work with torch tensors rather than numpy tensors

0. Creat a tensor:
x = torch.tensor([[1, 2], [3, 4]],
                 type=torch.float32,  # dtype (precision)              - default
                 evice='cpu',         # cpu/cuda for GPU               - default
                 requires_grad=False) # not param ie no grade no train - default
attributes:
print(x.shape)         # torch.Size([5, 3])
print(x.dtype)         # torch.float32, data can be int, params must be float for (gradient)
print(x.device)        # cpu
print(x.requires_grad) # trainable or not

1. Create from numpy array:
x = torch.tensor(train_x); print(x)

2. Generate data with a specific shape:
shape  = (44, 4)
ones   = torch.ones(shape)  # shape (44, 4) with all ones
zeros  = torch.zeros(shape) # shape (44, 4) with all zeros
random = torch.randn(shape) # shape (44, 4) with random numbers -3 to 3
random = torch.rand(shape)  # shape (44, 4) with uniform dist 0 to 1

3. Mimic another tensor (same shape and dtype):
mimic = torch.randn_like(x)
--------------------------------------------------------------------------------
X usually capital, mathematical notation of a tensor
y usually small, mathematical notation of a vector
--------------------------------------------------------------------------------
Global fuse random seed:
torch.manual_seed(42)
np.random.seed(42)
--------------------------------------------------------------------------------
Global device assinment
device = 'cuda' if torch.cuda.is_available() else 'cpu'
--------------------------------------------------------------------------------
Parameters need to be declared:
x = torch.randint(0, 10, (5, 3))           # Input data (int)
w = torch.rand((5, 3), requires_grad=True) # Trainable parameter weights (float)
--------------------------------------------------------------------------------
Where tensors came from
print(x.grad_fn) # None - it was declared
z = x + w
print(z.grad_fn) # AddBackward0 - it was generated by an addition
--------------------------------------------------------------------------------
* vs @ vs dot multiplication:
* is elementwise multiplication ⊙ - np.multiply()   shapes must be equal
@ is matrix multiplication      @ - np.matmul()     (_,#) = (#,_) dot products
. is dot product                . - np.dot()        matrix-vector multiplication
X * Y # elementwise multiplication
X @ Y # matrix multiplication
y = x@w + b <--- pay attention
--------------------------------------------------------------------------------
Reduction, reducing a tensor into smaller elements, sum() mean() max()
torch.score(x) # averages all elements in a tensor into a single value
torch.score(x, dim=0) dim=0 ↓ dim=1 →
torch.argmax(x, dim=1)
--------------------------------------------------------------------------------
Slicing [Row, Column, Channel]:
x[2]    # Slice row
x[:, 2] # Slice column
x[0, 0] # First item from row, first item from column
torch.gather(x, dim=1, index=[[2], [0], [3]]) # Gather elements from locations
--------------------------------------------------------------------------------
Gradient
W = torch.randn((3, 5), requires_grad=True)
print(W.grad)
torch.no_grad() # Freeze these parameters
.grad.zero()    # Reset to zero after each epoch
--------------------------------------------------------------------------------
Layer
# Logit no activation function
L1 = torch.nn.Linear(in_features=x_shape, out_features=y_hat_shape)
	# Example
	X = torch.randn((10, 1))
	layer_1 = torch.nn.Linear(1, 1)
	y_hat = layer_1(X)
	print(layer_1.weight)
	print(layer_1.bias)
	print(y_hat)
# Activation functions
torch.nn.ReLU(L1)
torch.nn.GELU(L1)
torch.nn.Softmax(L1)
torch.nn.Tanh(L1)
# Embedding layer
converts words into numbers
torch.nn.Embedding(vocab_size, embedding_dim)
# Normalisation
torch.nn.LayerNorm(normalisation_shape)     # Mini batch normalisation
torch.nn.Dropout(p=0.5)                     # Dropout normalisation
--------------------------------------------------------------------------------
Build the network
class FFW(torch.nn.Module):
	def __init__(self, in_features, out_features):
		super().__init__()
		self.L1 = torch.nn.Linear(in_features, 16)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(16, out_features)
	def forward(self, x):
		x = self.L1(x)
		x = self.A1(x)
		x = self.L2(x)   # technically this is building a nested setup self.L2(self.A1(self.L1(x)))
		return x
model = FFW(in_features=44, out_features=4)
print(model)
--------------------------------------------------------------------------------
Optimiser
optm = torch.optim.Adam(model.parameters(), lr=0.001)
pass in the parameters of the constructed model
--------------------------------------------------------------------------------
Loss
lossFN = torch.nn.MSELoss()
lossFN = torch.nn.CrossEntropyLoss()
--------------------------------------------------------------------------------
Training loop
for epoch in range(epochs):
	# --- Training --- #
	model.train()                 # Set train mode, will calculate param gradients and track them
	y_hat = model(X_train)        # Forward pass
	loss = loss_fn(y_hat, y_true) # Calculate loss between y_hat and y_true
	optimiser.zero_grad()         # Reset all param gradients
	loss.backward()               # Backpropagation to find new param gradients
	optimiser.step()              # Gradient discent step
	# --- Validation --- #
	model.eval()                  # Set eval mode to disable dropout & bachnorm
	with torch.inference_mode(),  # Freez gradients
		y_hat_val = model(X_val)  # Forward pass on validation set
		loss_val = loss_fn(y_hat_val, y_true_val) # Calculate loss
	print(epoch, loss.item(), loss_val.item())
--------------------------------------------------------------------------------
Save model:
torch.save(model.state_dict(), 'model.pt')
Load model:
model.load_state_dict(torch.load('model.pt'))
--------------------------------------------------------------------------------
Run prediction:
model.eval()
with torch.inference_mode(): # freezes grad tracking ie no param adjustments
    y_pred = model(X_test)
print(y_pred)
================================================================================
QUESTIONS:
1. why in FFW() no softmax?
2. why X dtype float32 while Y dtype is int64 and not int32?
'''

# Data
def line():
	w = 0.7
	b = 0.3
	start = 0
	end = 1
	step = 0.02
	X = torch.arange(start, end, step).unsqueeze(dim=1)
	y = w*X + b
	return X, y

def sine_data(samples=1000):
	''' Regression '''
	X = np.arange(samples).reshape(-1, 1) / samples
	y = np.sin(2 * np.pi * X).reshape(-1, 1)
	return X, y

def spiral_data(samples, classes):
	''' Binary or Categorical Classification '''
	X = np.zeros((samples*classes, 2))
	y = np.zeros(samples*classes, dtype='uint8')
	for class_n in range(classes):
		ix = range(samples*class_n, samples*(class_n+1))
		r = np.linspace(0.0, 1, samples)
		t = np.linspace(class_n*4, (class_n+1)*4, samples) + np.random.randn(samples)*0.2
		X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
		y[ix] = class_n
	return X, y
'''
### --- Regression --- ###
X, y_true = line()

# 1. Build model:
class REGRESSION(torch.nn.Module):
	def __init__(self):
		super().__init__()                          # Call the parent class's constructor
		self.W = torch.nn.Parameter(torch.randn(1)) # Same as self.W = torch.randn(1, requires_grad=True)
		self.B = torch.nn.Parameter(torch.randn(1)) # Better to use nn.Parameters to push to optimiser
	def forward(self, x):
		return self.W * x + self.B

model_R = REGRESSION()

# 2. Declare loss function and optimiser:
loss_fn = torch.nn.L1Loss()
optimiser = torch.optim.SGD(model_R.parameters(), lr=0.01)

# 3. Train model:
for epoch in range(1000):
	model_R.train()
	y_hat = model_R(X)
	loss = loss_fn(y_hat, y_true)
	optimiser.zero_grad()
	loss.backward()
	optimiser.step()
	print(loss.item())
print(model_R.state_dict())
'''

'''
### --- Binary Classification --- ###
X, y = spiral_data(samples=1000, classes=2)
y = y.reshape(-1, 1)
X = torch.from_numpy(X).type(torch.float32)
y = torch.from_numpy(y).type(torch.float32)

X, y = sklearn.utils.shuffle(X, y)
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, y)

# 1. Build model: # this allows us to build more complex networks
class BIN_CLASS(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.L1 = torch.nn.Linear(2, 10)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(10, 10)
		self.A2 = torch.nn.ReLU()
		self.L3 = torch.nn.Linear(10, 1)
	def forward(self, x):
		z = self.L1(x)
		z = self.A1(z)
		z = self.L2(z)
		z = self.A2(z)
		z = self.L3(z)
		return z

device = 'cpu'
model_B = BIN_CLASS().to(device)
print(model_B)

model_b = torch.nn.Sequential( # this allows us to only build FFE networks
	torch.nn.Linear(2, 8),
	torch.nn.Linear(8, 1)).to(device)

print(model_b)

# 2. Declare loss function and optimiser:
loss_fn = torch.nn.BCEWithLogitsLoss() # has sigmoid AF built in, as if adding nn.Sigmoid() at the end of the network then using nn.BCELoss()

optimiser = torch.optim.SGD(model_B.parameters(), lr=0.1)

def accuracy(y_true, y_hat):
	correct = torch.eq(y_true, y_hat).sum().item()
	acc = (correct / len(y_hat)) * 100
	return acc

# 3. Train model:
for epoch in range(10000):
	# --- Train --- #
	model_B.train()
	y_logits = model_B(x_train) # logits because output without activation function
	loss = loss_fn(y_logits, y_train) # calculate loss
	y_pred_prob = torch.sigmoid(y_logits) # puch logits through activation function
	y_hat = torch.round(y_pred_prob) # round the values to make the probability clearer for each class
	acc = accuracy(y_hat, y_train) # calcualte accuracy
	optimiser.zero_grad()
	loss.backward()
	optimiser.step()
	# --- Validation --- #
	model_B.eval() # Validaiton mode disable dropout and bachnorm
	with torch.inference_mode():
		y_logits_val = model_B(x_test)
		loss_val = loss_fn(y_logits_val, y_test)
		y_pred_val = torch.sigmoid(y_logits_val)
		y_hat_val = torch.round(y_pred_val)
		acc_val = accuracy(y_hat_val, y_test)
	print(loss.item(), acc, loss_val.item(), acc_val)

# 4. Run prediction
model_B.eval()
with torch.inference_mode():
	y_logits = model_B(x_test.to(device))

# Convert probabilities into class labels in this binary classification
#print(y_pred) # shape (500, 1)
#print(y_pred.squeeze()) # shape (500)
#print(torch.eq(y_pred.squeeze(), y_test.squeeze())) # compare pred to test labels
'''

'''
### --- Categorical Classification --- ###
X, y = spiral_data(samples=1000, classes=3)
X = torch.from_numpy(X).type(torch.float32)
y = torch.from_numpy(y).type(torch.long)

X, y = sklearn.utils.shuffle(X, y)
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, y)

# 1. Build model: # this allows us to build more complex networks
class CAT_CLASS(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.L1 = torch.nn.Linear(2, 512)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(512, 512)
		self.A2 = torch.nn.ReLU()
		self.L3 = torch.nn.Linear(512, 3)
	def forward(self, x):
		z = self.L1(x)
		z = self.A1(z)
		z = self.L2(z)
		z = self.A2(z)
		z = self.L3(z)
		return z

device = 'cpu'
model_C = CAT_CLASS().to(device)

# 2. Declare loss function and optimiser:
loss_fn = torch.nn.CrossEntropyLoss() # has softmax AF built in

optimiser = torch.optim.SGD(model_C.parameters(), lr=0.1)

def accuracy(y_hat, y_true):
	y_pred = torch.argmax(y_hat, dim=1)
	correct = (y_pred == y_true).sum().item()
	acc = (correct / len(y_hat)) * 100
	return acc

# 3. Train model:
for epoch in range(10000):
	# --- Train --- #
	model_C.train()
	y_logits = model_C(x_train)
	loss = loss_fn(y_logits, y_train)
	acc = accuracy(y_logits, y_train)
	optimiser.zero_grad()
	loss.backward()
	optimiser.step()
	# --- Validation --- #
	model_C.eval()
	with torch.inference_mode():
		y_logits_val = model_C(x_test)
		loss_val = loss_fn(y_logits_val, y_test)
		acc_val = accuracy(y_logits_val, y_test)
	print(loss.item(), acc, loss_val.item(), acc_val)
'''

'''
### --- CNN --- ###
import torchvision #pip install torchvision
from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader

train_data = datasets.FashionMNIST(root='./', train=True, download=True, transform=ToTensor(), target_transform=None)
tests_data = datasets.FashionMNIST(root='./', train=False, download=True, transform=ToTensor(), target_transform=None)

train_data_batches = DataLoader(dataset=train_data, batch_size=32, shuffle=True)
tests_data_batches = DataLoader(dataset=tests_data, batch_size=32, shuffle=True)
print(len(train_data_batches)) # 1875 batches divided into 32 examples each batches
print(len(tests_data_batches)) # 313  batches divided into 32 examples each batches

train_x_data_batches, train_y_data_batches = next(iter(train_data_batches))
tests_x_data_batches, tests_y_data_batches = next(iter(tests_data_batches))

print(train_x_data_batches.shape, train_y_data_batches.shape)
#         (32, 1, 28, 28)                (32) 32 example labels
#   32 examples, each example is 1 colour channels, 28 height, 28 width
print(train_x_data_batches[0].shape) # (1, 28, 28)

flatten_model = torch.nn.Flatten()
print(flatten_model(train_x_data_batches[0]).shape) # (1, 784) convert matrix to vector

#1. Build model

#class IMG_CLASS(torch.nn.Module):
#	def __init__(self, ins, hidden, outs):
#		super().__init__()
#		self.layer_stack = torch.nn.Sequential(
#		torch.nn.Flatten(),
#		torch.nn.Linear(ins, hidden),
#		torch.nn.Linear(hidden, outs),
#		)
#	def forward(self, x):
#		return self.layer_stack(x)
#number_of_classes=10
#model_I = IMG_CLASS(784, 10, 10).to('cpu')

class IMG_CLASS(torch.nn.Module):
	def __init__(self, ins, hidden, outs):
		super().__init__()
		self.block1 = torch.nn.Sequential(
			torch.nn.Conv2d(ins,    hidden, kernel_size=3, stride=1, padding=1),
			torch.nn.ReLU(),
			torch.nn.Conv2d(hidden, hidden, kernel_size=3, stride=1, padding=1),
			torch.nn.ReLU(),
			torch.nn.MaxPool2d(kernel_size=2))
		self.block2 = torch.nn.Sequential(
			torch.nn.Conv2d(hidden, hidden, kernel_size=3, stride=1, padding=1),
			torch.nn.ReLU(),
			torch.nn.Conv2d(hidden, hidden, kernel_size=3, stride=1, padding=1),
			torch.nn.ReLU(),
			torch.nn.MaxPool2d(kernel_size=2))
		self.FFW = torch.nn.Sequential(
			torch.nn.Flatten(),
			torch.nn.Linear(10*7*7, outs))# print('3', z.shape)->(32, 10, 7, 7) therefore 10*7*7
	def forward(self, x):
#		print('1', x.shape)
		z = self.block1(x)
#		print('2', z.shape)
		z = self.block2(z)
#		print('3', z.shape)
		z = self.FFW(z)
#		print('4', z.shape)
		return z

number_of_classes=10
model_I = IMG_CLASS(1, 10, 10).to('cpu')

# confirm model is working and giving output - first NN
#print(model_I(flatten_model(train_x_data_batches[0])))

# confirm model is working and giving output - CNN NN
print('test output', model_I(train_x_data_batches).shape)

loss_fn = torch.nn.CrossEntropyLoss()

optimiser = torch.optim.SGD(model_I.parameters(), lr=0.1)

def accuracy(y_hat, y_true):
	y_pred = torch.argmax(y_hat, dim=1)
	correct = (y_pred == y_true).sum().item()
	acc = (correct / y_true.size(0)) * 100
	return acc

from torchinfo import summary
summary(model_I)

# Training:
for epoch in range(1):
	# --- Training --- #
	train_loss = 0
	model_I.train()
	# bach loop
	for batch, (X, y) in enumerate(train_data_batches):
		y_pred = model_I(X)
		loss = loss_fn(y_pred, y)
		train_loss += loss        # accumelate loss over all batches
		optimiser.zero_grad()
		loss.backward()
		optimiser.step()
	train_loss /= len(train_data_batches)
	# --- Validation --- #
	test_loss = 0
	test_acc = 0
	model_I.eval()
	with torch.inference_mode():
		# bach loop
		for X_test, y_test in tests_data_batches:
			y_pred = model_I(X_test)
			loss = loss_fn(y_pred, y_test)
			test_loss += loss        # accumelate loss over all batches
			test_acc += accuracy(y_pred, y_test)
		test_loss /= len(tests_data_batches)
		test_acc /= len(tests_data_batches)
	print(train_loss.item(), test_loss.item(), test_acc)
'''

# Import local images and Augment them
# directory/set/class/images
# Food/train/pizza/img0001.jpg

from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader

# augment data: ===> Even though the count stays the same, the content changes every epoch
from torchvision import transforms

T = transforms.Compose([
	transforms.Resize((64, 64)),
	transforms.RandomHorizontalFlip(p=0.5),
	transforms.RandomRotation(15),
	transforms.RandomResizedCrop(64, scale=(0.8, 1.0)),
	transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
	transforms.ToTensor()])

train_data = datasets.ImageFolder(root='pizza_steak_sushi/train',
	transform=T, # transform/augment images
	target_transform=None) # transform labels (keep None)
tests_data = datasets.ImageFolder(root='pizza_steak_sushi/test',
	transform=T, # do not augment test set, just resize it
	target_transform=None)

# no augment
#train_data = datasets.ImageFolder(root='pizza_steak_sushi/train', transform=ToTensor(), target_transform=None)
#tests_data = datasets.ImageFolder(root='pizza_steak_sushi/test', transform=ToTensor(), target_transform=None)

train_data_batches = DataLoader(dataset=train_data, batch_size=32, shuffle=True)
tests_data_batches = DataLoader(dataset=tests_data, batch_size=32, shuffle=True)

print(len(train_data_batches))
images, labels = next(iter(train_data_batches))
print(images.shape)



'''
# Import data
data = pd.read_csv('fruits.csv')
X = data[['mass', 'width', 'height', 'color_score']].to_numpy()
Y = data['fruit_label'].to_numpy()
X, Y = sklearn.utils.shuffle(X, Y)
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(X, Y)

X = torch.tensor(train_x, dtype=torch.float32)
y_true = torch.tensor(train_y, dtype=torch.int64)

X_val = torch.tensor(valid_x, dtype=torch.float32)
y_true_val = torch.tensor(valid_y, dtype=torch.int64)

# Setup Network
class FFW(torch.nn.Module):
	def __init__(self, in_features, out_features):
		super().__init__()
		self.L1 = torch.nn.Linear(in_features, 16)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(16, out_features)
	def forward(self, x):
		x = self.L1(x)
		x = self.A1(x)
		x = self.L2(x)
		return x

model = FFW(in_features=4, out_features=4)

# Compile Model
optm = torch.optim.Adam(model.parameters(), lr=0.001)
lossFN = torch.nn.CrossEntropyLoss()

# Train Model
for epoch in range(10):
	# --- Training --- #
	model.train() # Training mode
	y_hat = model(X)
	loss = lossFN(y_hat, y_true)
	optm.zero_grad()
	loss.backward()
	optm.step()
	# --- Validation --- #
	model.eval() # Validaiton mode disable dropout and bachnorm
	with torch.no_grad():
		y_hat_val = model(X_val)
		loss_val = lossFN(y_hat_val, y_true_val)
	print(epoch, loss.item(), loss_val.item())
'''
