import torch # pip install torch numpy pandas scikit-learn
import sklearn
import numpy as np
import pandas as pd
from sklearn import model_selection

# Import data
data = pd.read_csv('fruits.csv')
X = data[['mass', 'width', 'height', 'color_score']].to_numpy()
Y = data['fruit_label'].to_numpy()
X, Y = sklearn.utils.shuffle(X, Y)
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(X, Y)

'''
Concepts:
=========
We work with torch tensors rather than numpy tensors

1. Create from numpy array:
x = torch.tensor(train_x); print(x)

2. Generate data with a specific shape:
shape  = (44, 4)
ones   = torch.ones(shape)  # shape (44, 4) with all ones
zeros  = torch.zeros(shape) # shape (44, 4) with all zeros
random = torch.randn(shape) # shape (44, 4) with random numbers -3 to 3
random = torch.rand(shape)  # shape (44, 4) with uniform dist 0 to 1

3. Mimic another tensor (same shape and dtype):
template = torch.tensor([[1, 2], [3, 4]])
mimic = torch.randn_like(tempalte)
--------------------------------------------------------------------------------
Tensors have attributes:
x = torch.rand((5, 3))
print(x.shape)  # torch.Size([5, 3])
print(x.dtype)  # torch.float32, data can be int params must be float (gradient)
print(x.device) # cpu
--------------------------------------------------------------------------------
Parameters need to be declared:
x = torch.randint(0, 10, (5, 3))           # Input data (int)
w = torch.rand((5, 3), requires_grad=True) # Trainable parameter weights (float)
--------------------------------------------------------------------------------
Where tensors came from
print(x.grad_fn) # None - it was declared
z = x + w
print(z.grad_fn) # AddBackward0 - it was generated by an addition
--------------------------------------------------------------------------------
* vs @ vs dot multiplication:
* is elementwise multiplication ⊙ - np.multiply()   shapes must be equal
@ is matrix multiplication      @ - np.matmul()     (_,#) = (#,_) dot products
. is dot product                . - np.dot()        matrix-vector multiplication
X * Y # elementwise multiplication
X @ Y # matrix multiplication
y = x@w + b <--- pay attention
--------------------------------------------------------------------------------
Reduction, reducing a tensor into smaller elements, sum() mean() max()
torch.score(x) # averages all elements in a tensor into a single value
torch.score(x, dim=0) dim=0 ↓ dim=1 →
torch.argmax(x, dim=1)
--------------------------------------------------------------------------------
Slicing [Row, Column, Channel]:
x[2]    # Slice row
x[:, 2] # Slice column
x[0, 0] # First item from row, first item from column
torch.gather(x, dim=1, index=[[2], [0], [3]]) # Gather elements from locations
--------------------------------------------------------------------------------
Gradient
W = torch.randn((3, 5), requires_grad=True)
print(W.grad)
torch.no_grad() # Freeze these parameters
.grad.zero()    # Reset to zero after each epoch
--------------------------------------------------------------------------------
Layer
# Logit no activation function
L1 = torch.nn.Linear(in_features=x_shape, out_features=y_hat_shape)
	# Example
	X = torch.randn((10, 1))
	layer_1 = torch.nn.Linear(1, 1)
	y_hat = layer_1(X)
	print(layer_1.weight)
	print(layer_1.bias)
	print(y_hat)
# Activation functions
torch.nn.ReLU(L1)
torch.nn.GELU(L1)
torch.nn.Softmax(L1)
torch.nn.Tanh(L1)
# Embedding layer
converts words into numbers
torch.nn.Embedding(vocab_size, embedding_dim)
# Normalisation
torch.nn.LayerNorm(normalisation_shape)     # Mini batch normalisation
torch.nn.Dropout(p=0.5)                     # Dropout normalisation
--------------------------------------------------------------------------------
Build the network
class FFW(torch.nn.Module):
	def __init__(self, in_features, out_features):
		super().__init__()
		self.L1 = torch.nn.Linear(in_features, 16)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(16, out_features)
	def forward(self, x):
		x = self.L1(x)
		x = self.A1(x)
		x = self.L2(x)
		return x
model = FFW(in_features=44, out_features=4)
print(model)
--------------------------------------------------------------------------------
Optimiser
optm = torch.optim.Adam(model.parameters(), lr=0.001)
pass in the parameters of the constructed model
--------------------------------------------------------------------------------
Loss
lossFN = torch.nn.MSELoss()
lossFN = torch.nn.CrossEntropyLoss()
--------------------------------------------------------------------------------
Training loop
for epoch in range(epochs):
	y_hat = model(X)                       # Get forward pass output from model
	loss = lossFN(y_hat, y_true)           # Calc loss between y_hat & y_true
	optm.zero_grad()                       # Zero the gradients of all params
	loss.backward()                        # Compute new gradients for params
	optm.step()                            # Update params
	print(epoch, loss.item())
'''

X = torch.tensor(train_x, dtype=torch.float32)
y_true = torch.tensor(train_y, dtype=torch.long)

X_val = torch.tensor(valid_x, dtype=torch.float32)
y_true_val = torch.tensor(valid_y, dtype=torch.long)

# Setup Network
class FFW(torch.nn.Module):
	def __init__(self, in_features, out_features):
		super().__init__()
		self.L1 = torch.nn.Linear(in_features, 16)
		self.A1 = torch.nn.ReLU()
		self.L2 = torch.nn.Linear(16, out_features)
	def forward(self, x):
		x = self.L1(x)
		x = self.A1(x)
		x = self.L2(x)
		return x

model = FFW(in_features=4, out_features=4)

# Compile Model
optm = torch.optim.Adam(model.parameters(), lr=0.001)
lossFN = torch.nn.CrossEntropyLoss()

# Train Model
for epoch in range(100000):
	# --- Training --- #
	model.train() # Training mode
	y_hat = model(X)
	loss = lossFN(y_hat, y_true)
	optm.zero_grad()
	loss.backward()
	optm.step()
	# --- Validation --- #
	model.eval() # Validaiton mode disable dropout and bachnorm
	with torch.no_grad():
		y_hat_val = model(X_val)
		loss_val = lossFN(y_hat_val, y_true_val)
	print(epoch, loss.item(), loss_val.item())

# Save Model
torch.save(model.state_dict(), 'model.pth')

# Load Model
model.load_state_dict(torch.load('model.pth'))

# Model Prediction
model.eval()
with torch.no_grad():
	pred = model(X_val)

print(y_true_val)
print(torch.argmax(pred, dim=1))
