#!/bin/bash

{ROSETTA}/main/source/bin/combine_silent.default.linuxgccrelease -out::file::silent_struct_type binary -in:file:silent FFL_silent_*.out -out:file:silent FFL_silent.out
rm FFL_silent_*.out
mkdir lowest_20
grep SCORE FFL_silent.out | sort -nk +2 | head -20 | awk '{print $2 "\t" $14 "\t" $25 "\t" $28}' > lowest_20/list_20_score
cat lowest_20/list_20_score | sort -nk +2 | head -20 | awk '{print $3}' > lowest_20/list_20_rmsd
cat lowest_20/list_20_rmsd | awk '{print}' ORS=" " > lowest_20/list_20_rmsd_string
cd lowest_20
xargs {ROSETTA}/main/source/bin/extract_pdbs.linuxgccrelease -in::file::silent {PATH}/FFL_silent.out -out:pdb -in:file:tags < list_20_rmsd_string
rm list_20_rmsd
rm list_20_rmsd_string
rm {PATH}/*.pdb
