#!/bin/bash
#PBS -N gmx
#PBS -q thin
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=24
#PBS -j oe

cd $PBS_O_WORKDIR

<<COMMENT
Required Files:
1. The .pbs script
2. The .pdb file
COMMENT

#-------------------------------------------------------------------------------

# Prepare The Protein File
P=1
mkdir -p MD_Simulation_$P/RawData
mv $P.pdb MD_Simulation_$P/RawData
cd MD_Simulation_$P/RawData

# Construct The .mdp Files
echo '
integrator           = steep
emtol                = 1000.0
emstep               = 0.01
nsteps               = 50000
nstlist              = 1
cutoff-scheme        = Verlet
ns_type              = grid
coulombtype          = PME
rcoulomb             = 1.0
rvdw                 = 1.0
pbc                  = xyz
'>>ions.mdp

echo '
integrator           = steep
emtol                = 1000.0
emstep               = 0.01
nsteps               = 50000
nstlist              = 1
cutoff-scheme        = Verlet
ns_type              = grid
coulombtype          = PME
rcoulomb             = 1.0
rvdw                 = 1.0
pbc                  = xyz
'>>minim.mdp

echo '
define               = -DPOSRES
integrator           = md
nsteps               = 50000
dt                   = 0.002
nstxout              = 500
nstvout              = 500
nstenergy            = 500
nstlog               = 500
continuation         = no
constraint_algorithm = lincs
constraints          = all-bonds
lincs_iter           = 1
lincs_order          = 4
cutoff-scheme        = Verlet
ns_type              = grid
nstlist              = 10
rcoulomb             = 1.0
rvdw                 = 1.0
coulombtype          = PME
pme_order            = 4
fourierspacing       = 0.16
tcoupl               = V-rescale
tc-grps              = Protein Non-Protein
tau_t                = 0.1  0.1
ref_t                = 300  300
pcoupl               = no
pbc                  = xyz
DispCorr             = EnerPres
gen_vel              = yes
gen_temp             = 300
gen_seed             = -1
'>>nvt.mdp

echo '
define               = -DPOSRES
integrator           = md
nsteps               = 50000
dt                   = 0.002
nstxout              = 500
nstvout              = 500
nstenergy            = 500
nstlog               = 500
continuation         = yes
constraint_algorithm = lincs
constraints          = all-bonds
lincs_iter           = 1
lincs_order          = 4
cutoff-scheme        = Verlet
ns_type              = grid
nstlist              = 10
rcoulomb             = 1.0
rvdw                 = 1.0
coulombtype          = PME
pme_order            = 4
fourierspacing       = 0.16
tcoupl               = V-rescale
tc-grps              = Protein Non-Protein
tau_t                = 0.1  0.1
ref_t                = 300  300
pcoupl               = Parrinello-Rahman
pcoupltype           = isotropic
tau_p                = 2.0
ref_p                = 1.0
compressibility      = 4.5e-5
refcoord_scaling     = com
pbc                  = xyz
DispCorr             = EnerPres
gen_vel              = no
'>>npt.mdp

echo '
integrator           = md
nsteps               = 50000000
dt                   = 0.002
nstxout              = 5000
nstvout              = 5000
nstenergy            = 5000
nstlog               = 5000
nstxout-compressed   = 5000
compressed-x-grps    = System
continuation         = yes
constraint_algorithm = lincs
constraints          = all-bonds
lincs_iter           = 1
lincs_order          = 4
cutoff-scheme        = Verlet
ns_type              = grid
nstlist              = 10
rcoulomb             = 1.0
rvdw                 = 1.0
coulombtype          = PME
pme_order            = 4
fourierspacing       = 0.16
tcoupl               = V-rescale
tc-grps              = Protein Non-Protein
tau_t                = 0.1  0.1
ref_t                = 300  300
pcoupl               = Parrinello-Rahman
pcoupltype           = isotropic
tau_p                = 2.0
ref_p                = 1.0
compressibility      = 4.5e-5
pbc                  = xyz
DispCorr             = EnerPres
gen_vel              = no
;annealing            = single
;annealing-npoints    = 3
;annealing-time       = 0 2000 400
;annealing-temp       = 0 300 350 400
'>>md.mdp

# Prepare The System
printf %s\\n 15 | gmx pdb2gmx -f $P.pdb -o $P.gro -water spce -ignh
gmx editconf -f $P.gro -o $P\_box.gro -c -d 1.0 -bt dodecahedron
gmx solvate -cp $P\_box.gro -cs spc216.gro -o $P\_solv.gro -p topol.top
gmx grompp -f ions.mdp -c $P\_solv.gro -p topol.top -o ions.tpr -maxwarn 1
charge=$(grep qtot topol.top | tail -n 1 | awk 'NF>1{print $NF}')
if [[ $charge -le "0" ]]; then
    charge=$(( $charge * -1 ))
    printf %s\\n 13 | gmx genion -s ions.tpr -o $P\_solv\_ions.gro -p topol.top -pname NA -nname CL -nn 0 -np $charge
else
    printf %s\\n 13 | gmx genion -s ions.tpr -o $P\_solv\_ions.gro -p topol.top -pname NA -nname CL -nn $charge -np 0
fi
gmx grompp -f minim.mdp -c $P\_solv_ions.gro -p topol.top -o em.tpr
gmx mdrun -deffnm em
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
gmx mdrun -deffnm nvt
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx mdrun -deffnm npt
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr

# Run molecular dynamics simulation
time gmx mdrun -deffnm md

# Analysis
printf %s\\n 0 | gmx trjconv -f md.trr -s md.tpr -o MD.pdb -pbc mol -ur compact
mv Simulation.pdb ..
printf %s\\n 0 | gmx trjconv -s md.tpr -f md.xtc -o md.xtc -pbc mol -ur compact
printf %s\\n 14 | gmx energy -s md.tpr -f md.edr -o temperature.xvg
sed -i 's/@/#/g' temperature.xvg
printf %s\\n 4 \n 4 | gmx rms -s md.tpr -f md.xtc -o rmsd.xvg
sed -i 's/@/#/g' rmsd.xvg
printf %s\\n 4 \n 4 | gmx rms -s em.tpr -f md.xtc -o rmsd_crystal.xvg
sed -i 's/@/#/g' rmsd_crystal.xvg
printf %s\\n 4 | gmx gyrate -s md.tpr -f md.xtc -o gyrate.xvg
sed -i 's/@/#/g' gyrate.xvg

echo "
reset
set terminal pdfcairo
set encoding iso_8859_1
set term post eps enh color
set output './Results.pdf'
set title 'MD simulation results'
set grid
set xlabel 'Time (ps)'
set ylabel 'RMSD (\305)'
set y2label 'Temperature (K)'
set y2tics
set ytics nomirror
plot \
'temperature.xvg' w l title 'Temperature' axis x1y2 lc rgb 'blue',\
'rmsd.xvg' u 1:(column(2)*10) w l title 'RMSD' axis x1y1 lc rgb 'red',\
'gyrate.xvg' u 1:(column(2)*10) w l title 'Rg' axis x1y1 lc rgb 'green'
">>gnu.plot
gnuplot -p gnu.plot
rm gnu.plot
