#!/bin/bash
#PBS -N gmx
#PBS -q thin
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=24
#PBS -j oe

cd $PBS_O_WORKDIR

<<COMMENT
Required Files:
1. The .pbs script
2. The .pdb file
COMMENT

#-------------------------------------------------------------------------------

# Prepare The Protein File
P=1
mkdir -p MD_Simulation_$P/RawData
mv $P.pdb MD_Simulation_$P/RawData
cd MD_Simulation_$P/RawData

#Construct The .mdp Files
echo '
integrator           = steep               ; Algorithm (steep = steepest descent minimization)
emtol                = 1000.0              ; Stop minimization when the maximum force < 1000.0 kJ/mol/nm
emstep               = 0.01                ; Energy step size
nsteps               = 50000               ; Maximum number of (minimization) steps to perform
; Parameters describing how to find the neighbors of each atom and how to calculate the interactions
nstlist              = 1                   ; Frequency to update the neighbor list and long range forces
cutoff-scheme        = Verlet
ns_type              = grid                ; Method to determine neighbor list (simple, grid)
coulombtype          = PME                 ; Treatment of long range electrostatic interactions
rcoulomb             = 1.0                 ; Short-range electrostatic cut-off
rvdw                 = 1.0                 ; Short-range Van der Waals cut-off
pbc                  = xyz                 ; Periodic Boundary Conditions (yes/no)
'>>ions.mdp

echo '
integrator           = steep               ; Algorithm (steep = steepest descent minimization)
emtol                = 1000.0              ; Stop minimization when the maximum force < 1000.0 kJ/mol/nm
emstep               = 0.01                ; Energy step size
nsteps               = 50000               ; Maximum number of (minimization) steps to perform
; Parameters describing how to find the neighbors of each atom and how to calculate the interactions
nstlist              = 1                   ; Frequency to update the neighbor list and long range forces
cutoff-scheme        = Verlet
ns_type              = grid                ; Method to determine neighbor list (simple, grid)
coulombtype          = PME                 ; Treatment of long range electrostatic interactions
rcoulomb             = 1.0                 ; Short-range electrostatic cut-off
rvdw                 = 1.0                 ; Short-range Van der Waals cut-off
pbc                  = xyz                 ; Periodic Boundary Conditions (yes/no)
'>>minim.mdp

echo '
define               = -DPOSRES            ; position restrain the protein
; Run parameters
integrator           = md                  ; leap-frog integrator
nsteps               = 50000               ; 2 * 50000 = 100 ps
dt                   = 0.002               ; 2 fs
; Output control
nstxout              = 500                 ; save coordinates every 1.0 ps
nstvout              = 500                 ; save velocities every 1.0 ps
nstenergy            = 500                 ; save energies every 1.0 ps
nstlog               = 500                 ; update log file every 1.0 ps
; Bond parameters
continuation         = no                  ; first dynamics run
constraint_algorithm = lincs               ; holonomic constraints 
constraints          = all-bonds           ; all bonds (even heavy atom-H bonds) constrained
lincs_iter           = 1                   ; accuracy of LINCS
lincs_order          = 4                   ; also related to accuracy
; Neighborsearching
cutoff-scheme        = Verlet
ns_type              = grid                ; search neighboring grid cells
nstlist              = 10                  ; 20 fs, largely irrelevant with Verlet
rcoulomb             = 1.0                 ; short-range electrostatic cutoff (in nm)
rvdw                 = 1.0                 ; short-range van der Waals cutoff (in nm)
; Electrostatics
coulombtype          = PME                 ; Particle Mesh Ewald for long-range electrostatics
pme_order            = 4                   ; cubic interpolation
fourierspacing       = 0.16                ; grid spacing for FFT
; Temperature coupling is on
tcoupl               = V-rescale           ; modified Berendsen thermostat
tc-grps              = Protein Non-Protein ; two coupling groups - more accurate
tau_t                = 0.1  0.1            ; time constant, in ps
ref_t                = 300  300            ; reference temperature, one for each group, in K
; Pressure coupling is off
pcoupl               = no                  ; no pressure coupling in NVT
; Periodic boundary conditions
pbc                  = xyz                 ; 3-D PBC
; Dispersion correction
DispCorr             = EnerPres            ; account for cut-off vdW scheme
; Velocity generation
gen_vel              = yes                 ; assign velocities from Maxwell distribution
gen_temp             = 300                 ; temperature for Maxwell distribution
gen_seed             = -1                  ; generate a random seed
'>>nvt.mdp

echo '
define               = -DPOSRES            ; position restrain the protein
; Run parameters
integrator           = md                  ; leap-frog integrator
nsteps               = 50000               ; 2 * 50000 = 100 ps
dt                   = 0.002               ; 2 fs
; Output control
nstxout              = 500                 ; save coordinates every 1.0 ps
nstvout              = 500                 ; save velocities every 1.0 ps
nstenergy            = 500                 ; save energies every 1.0 ps
nstlog               = 500                 ; update log file every 1.0 ps
; Bond parameters
continuation         = yes                 ; Restarting after NVT 
constraint_algorithm = lincs               ; holonomic constraints 
constraints          = all-bonds           ; all bonds (even heavy atom-H bonds) constrained
lincs_iter           = 1                   ; accuracy of LINCS
lincs_order          = 4                   ; also related to accuracy
; Neighborsearching
cutoff-scheme        = Verlet
ns_type              = grid                ; search neighboring grid cells
nstlist              = 10                  ; 20 fs, largely irrelevant with Verlet scheme
rcoulomb             = 1.0                 ; short-range electrostatic cutoff (in nm)
rvdw                 = 1.0                 ; short-range van der Waals cutoff (in nm)
; Electrostatics
coulombtype          = PME                 ; Particle Mesh Ewald for long-range electrostatics
pme_order            = 4                   ; cubic interpolation
fourierspacing       = 0.16                ; grid spacing for FFT
; Temperature coupling is on
tcoupl               = V-rescale           ; modified Berendsen thermostat
tc-grps              = Protein Non-Protein ; two coupling groups - more accurate
tau_t                = 0.1  0.1            ; time constant, in ps
ref_t                = 300  300            ; reference temperature, one for each group, in K
; Pressure coupling is on
pcoupl               = Parrinello-Rahman   ; Pressure coupling on in NPT
pcoupltype           = isotropic           ; uniform scaling of box vectors
tau_p                = 2.0                 ; time constant, in ps
ref_p                = 1.0                 ; reference pressure, in bar
compressibility      = 4.5e-5              ; isothermal compressibility of water, bar^-1
refcoord_scaling     = com
; Periodic boundary conditions
pbc                  = xyz                 ; 3-D PBC
; Dispersion correction
DispCorr             = EnerPres            ; account for cut-off vdW scheme
; Velocity generation
gen_vel              = no                  ; Velocity generation is off 
'>>npt.mdp

echo '
; Run parameters
integrator           = md                  ; leap-frog integrator
nsteps               = 500000              ; 0.002 (dt) * 500000 (nsteps) = 1000 ps (1 ns) | 0.002 (dt) * 50,000,000 (nsteps) = 100,000 ps (100 ns)
dt                   = 0.002               ; 2 fs
; Output control
nstxout              = 5000                ; save coordinates every 10.0 ps
nstvout              = 5000                ; save velocities every 10.0 ps
nstenergy            = 5000                ; save energies every 10.0 ps
nstlog               = 5000                ; update log file every 10.0 ps
nstxout-compressed   = 5000                ; save compressed coordinates every 10.0 ps
; nstxout-compressed replaces nstxtcout
compressed-x-grps    = System              ; replaces xtc-grps
; Bond parameters
continuation         = yes                 ; Restarting after NPT
constraint_algorithm = lincs               ; holonomic constraints
constraints          = all-bonds           ; all bonds (even heavy atom-H bonds) constrained
lincs_iter           = 1                   ; accuracy of LINCS
lincs_order          = 4                   ; also related to accuracy
; Neighborsearching
cutoff-scheme        = Verlet
ns_type              = grid                ; search neighboring grid cells
nstlist              = 10                  ; 20 fs, largely irrelevant with Verlet scheme
rcoulomb             = 1.0                 ; short-range electrostatic cutoff (in nm)
rvdw                 = 1.0                 ; short-range van der Waals cutoff (in nm)
; Electrostatics
coulombtype          = PME                 ; Particle Mesh Ewald for long-range electrostatics
pme_order            = 4                   ; cubic interpolation
; Temperature coupling is on
fourierspacing       = 0.16                ; grid spacing for FFT
tcoupl               = V-rescale           ; modified Berendsen thermostat
tc-grps              = Protein Non-Protein ; two coupling groups - more accurate
tau_t                = 0.1  0.1            ; time constant, in ps
ref_t                = 300  300            ; reference temperature, one for each group, in K
; Pressure coupling is on
pcoupl               = Parrinello-Rahman   ; Pressure coupling on in NPT
pcoupltype           = isotropic           ; uniform scaling of box vectors
tau_p                = 2.0                 ; time constant, in ps
ref_p                = 1.0                 ; reference pressure, in bar
compressibility      = 4.5e-5              ; isothermal compressibility of water, bar^-1
; Periodic boundary conditions
pbc                  = xyz                 ; 3-D PBC
; Dispersion correction
DispCorr             = EnerPres            ; account for cut-off vdW scheme
; Velocity generation
gen_vel              = no                  ; Velocity generation is off
;annealing            = single single       ; Type of annealing for each temperature group (no/single/periodic) (look at tc-grps [the thermostat group] there are 2 groups one for protein and the other for non-protein, therefore there are 2 groups. Therefore, here we write single (Protein) single (Non-Protein))
;annealing-npoints    = 2 2                 ; Number of time points to use for specifying annealing in each group (2 means two reference points to change the temperature, i.e start and finish, we want to start at 0ps with x temperature and end at 1000ps with y temperature) (3 means three reference points, i.e at 0ps, at 500ps, at 1000ps)
;annealing-time       = 0 1000 0 1000       ; List of times at the annealing points for each group (group 1 [Protein] start at 0 and end at 1000) (group 2 [Non-Protein] start at 0 and end at 1000)
;annealing-temp       = 0 500  0 500        ; Temp. at each annealing point, for each group (group 1 [Protein] start at 0 and end at 500) (group 2 [Non-Protein] start at 0 and end at 500)
'>>md.mdp

# Prepare The System
printf %s\\n 15 | gmx pdb2gmx -f $P.pdb -o $P.gro -water spce -ignh
gmx editconf -f $P.gro -o $P\_box.gro -c -d 1.0 -bt dodecahedron
gmx solvate -cp $P\_box.gro -cs spc216.gro -o $P\_solv.gro -p topol.top
gmx grompp -f ions.mdp -c $P\_solv.gro -p topol.top -o ions.tpr -maxwarn 1
charge=$(grep qtot topol.top | tail -n 1 | awk 'NF>1{print $NF}')
if [[ $charge -le "0" ]]; then
    charge=$(( $charge * -1 ))
    printf %s\\n 13 | gmx genion -s ions.tpr -o $P\_solv\_ions.gro -p topol.top -pname NA -nname CL -nn 0 -np $charge
else
    printf %s\\n 13 | gmx genion -s ions.tpr -o $P\_solv\_ions.gro -p topol.top -pname NA -nname CL -nn $charge -np 0
fi
gmx grompp -f minim.mdp -c $P\_solv_ions.gro -p topol.top -o em.tpr
gmx mdrun -deffnm em
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
gmx mdrun -deffnm nvt
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx mdrun -deffnm npt
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md.tpr

# Run molecular dynamics simulation
time gmx mdrun -deffnm md

# Analysis
printf %s\\n 0 | gmx trjconv -f md.trr -s md.tpr -o MD.pdb -pbc mol -ur compact
mv MD.pdb ..
printf %s\\n 0 | gmx trjconv -s md.tpr -f md.xtc -o md.xtc -pbc mol -ur compact
printf %s\\n 14 | gmx energy -s md.tpr -f md.edr -o temperature.xvg
sed -i 's/@/#/g' temperature.xvg
printf %s\\n 4 \n 4 | gmx rms -s md.tpr -f md.xtc -o rmsd.xvg
sed -i 's/@/#/g' rmsd.xvg
printf %s\\n 4 \n 4 | gmx rms -s em.tpr -f md.xtc -o rmsd_crystal.xvg
sed -i 's/@/#/g' rmsd_crystal.xvg
printf %s\\n 4 | gmx gyrate -s md.tpr -f md.xtc -o gyrate.xvg
sed -i 's/@/#/g' gyrate.xvg

echo "
reset
set terminal pdfcairo
set encoding iso_8859_1
set term post eps enh color
set output '../Results.pdf'
set title 'MD simulation results'
set grid
set xlabel 'Time (ps)'
set ylabel 'RMSD (\305)'
set y2label 'Temperature (K)'
set y2tics
set ytics nomirror
plot \
'temperature.xvg' w l title 'Temperature' axis x1y2 lc rgb 'blue',\
'rmsd.xvg' u 1:(column(2)*10) w l title 'RMSD' axis x1y1 lc rgb 'red',\
'gyrate.xvg' u 1:(column(2)*10) w l title 'Rg' axis x1y1 lc rgb 'green'
">>gnu.plot
gnuplot -p gnu.plot
rm gnu.plot
